# Generated by Django 3.1.3 on 2020-12-14 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('under_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('text', models.TextField()),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Published', 'published'), ('Draft', 'draft')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
    ]
