# Generated by Django 3.1.3 on 2020-12-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted',
            new_name='published',
        ),
    ]
