# Generated by Django 3.1.3 on 2020-12-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20201214_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
