# Generated by Django 3.1.3 on 2020-12-19 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20201216_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('under_title', models.CharField(blank=True, default='_', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('text', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='under_title',
            field=models.CharField(blank=True, default='_', max_length=255, null=True),
        ),
    ]
