# Generated by Django 3.1.4 on 2020-12-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20201219_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='under_title',
            field=models.CharField(blank=True, default='  ', max_length=255, null=True),
        ),
    ]
